# Generated by Django 2.1.4 on 2018-12-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='code',
            field=models.TextField(default='print("Hello Snippets")'),
        ),
    ]
